% Check that we have an unconstrained function bundle
function checkUnconstrainedFunctionsT(name,value)

    % Check for the appropriate fields
    if ~(checkFields({ ...
        'f', ...
        'PH'}, ...
        value))
        error(sprintf( ...
            'The %s argument must have type Unconstrained.Functions.t.',name));
    end
end
